// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsAnRCR5japMja3nN1LGjsxc_MUbCGoPY',
    appId: '1:894396928045:web:09899f4dcadab4e51068a4',
    messagingSenderId: '894396928045',
    projectId: 'appy-fa372',
    authDomain: 'appy-fa372.firebaseapp.com',
    storageBucket: 'appy-fa372.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAOD54owFPP-jLy3GqJdpWxmcz8xOtaTE',
    appId: '1:894396928045:android:aadd11c87fd239361068a4',
    messagingSenderId: '894396928045',
    projectId: 'appy-fa372',
    storageBucket: 'appy-fa372.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHgy6KHDrwRv7XSR7PL84npmNgToKhAwQ',
    appId: '1:894396928045:ios:4b0a62bd886582ef1068a4',
    messagingSenderId: '894396928045',
    projectId: 'appy-fa372',
    storageBucket: 'appy-fa372.firebasestorage.app',
    iosBundleId: 'com.example.appy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHgy6KHDrwRv7XSR7PL84npmNgToKhAwQ',
    appId: '1:894396928045:ios:4b0a62bd886582ef1068a4',
    messagingSenderId: '894396928045',
    projectId: 'appy-fa372',
    storageBucket: 'appy-fa372.firebasestorage.app',
    iosBundleId: 'com.example.appy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsAnRCR5japMja3nN1LGjsxc_MUbCGoPY',
    appId: '1:894396928045:web:9fb59fc28c5d513b1068a4',
    messagingSenderId: '894396928045',
    projectId: 'appy-fa372',
    authDomain: 'appy-fa372.firebaseapp.com',
    storageBucket: 'appy-fa372.firebasestorage.app',
  );
}
